# Generated by Django 5.2.6 on 2025-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_conductor',
            field=models.BooleanField(default=False),
        ),
    ]
